// <auto-generated />
namespace DemoEF6CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConstraintsOnDatbase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConstraintsOnDatbase));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011834261_ConstraintsOnDatbase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
